---
deployment:
  tasks:
    - export DEPLOYPATH=/home/YOUR_USERNAME/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .env.production $DEPLOYPATH/.env
    - cd $DEPLOYPATH && composer install --no-dev --optimize-autoloader
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:cache
    - cd $DEPLOYPATH && php artisan migrate --force
